name: static_file
description: An example showing how to
version: 0.0.1
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.23
  path:

dev_dependencies:
  test: ^0.12.0
